23 backend create api endpoint for test and submission crud
dangvuthang/rocodingtest pull request #31
Opened 2022-04-01 20:31 UTC by MyQuynh

2022-04-02 16:41 UTC, dangvuthang requested changes
When I run the program, it appears that you config `typescript` to not allow any unused variable like the image below. Please fix it first and ensure the program runs correctly without any errors 

 ![Screenshot (576)](https://user-images.githubusercontent.com/43143636/161392503-0a55f903-0b84-4d1c-bddf-a9142cfc93d3.png)

I see that in your `SubmissionController.ts`, and `TestController.ts` you use `async function` however you did not catch any expection, which would cause the whole server to crash if not handled carefully. You can learn more about it here [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

2022-04-02 17:15 UTC, MyQuynh commented
> When I run the program, it appears that you config `typescript` to not allow any unused variable like the image below. Please fix it first and ensure the program runs correctly without any errors
> 
> ![Screenshot (576)](https://user-images.githubusercontent.com/43143636/161392503-0a55f903-0b84-4d1c-bddf-a9142cfc93d3.png)
> 
> I see that in your `SubmissionController.ts`, and `TestController.ts` you use `async function` however you did not catch any expection, which would cause the whole server to crash if not handled carefully. You can learn more about it here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
> 
> There are still some issues, but these problems are your priority now

Wonder if my changes were satisfied your point of view, please let me know.

2022-04-02 17:54 UTC, dangvuthang requested changes
- Does folder `.vscode` required for backend to work ? If not please consider deleting it since I think you add it by mistake.
- In `SubmissionRoute.ts` and `TestRoute.ts`, you should structure route with no **params** `/` first before other route so that it is easy to follow
- `TestController.ts` async function `deleteTest` still hasn't been error handling
- `TestController.ts` async function `createTest` logic should be checked since we are going to generate a dyamic link, backend will be responsible for the task. First, we should generate `_id` for this document, you can use `mongoose.Types.ObjectId` to dynamically generate unique ObjectId then the `link` should look like this `localhost:3000/exam/_id` then save both the `link`, and `_id` to the db (Include them in `Test.create()`)
- Don't use `send` to send back response to `client`. Please send a json response (`.json`) with these fields `status` to indicate whether the operation succeed (success, fail, or error). Then if `success` include a `data` field that hold the actual value you want to send back to client. Incase of `fail` or `error`, include a `message` field

2022-04-02 18:42 UTC, MyQuynh commented
For the `link` field, I will make a quite different approach to your suggestion. In stead of doing that in Test.create(), I will have another function in `TestModel` that sets the `link` default fields to `localhost:3000/exam/_id`.

2022-04-04 03:53 UTC, dangvuthang requested changes
`checkIfTeacher` in your `TestController.ts` has redundant logic, and wrong implementation. 

- Since we already include `routes.use(checkMicrosoftLogin, checkAccountInDb)`, you can be sure that if a request pass `checkAccountInDb` middleware, it means we already found an account of the current logged-in user with that token. You can just use `if(req.user && req.user.role === "teacher")` to conditional check if the current user is a **teacher** instead of looking up on the db again.  
-  This method should be a middleware meaning apart from checking if the user is a teacher, only when exception arrived should it terminate the req-res cycle. However, you did use `res.send` on every if path. This would cause the next middleware in the stack routes.post("/") to become unreachable. If the current request is a teacher just say `return next()` to indicate that it is ok to pass. Please refer to [https://expressjs.com/en/guide/using-middleware.html] (https://expressjs.com/en/guide/using-middleware.html) for more detail

2022-04-05 01:22 UTC, dangvuthang commented on backend/src/models/User.ts
> +    roles: string;
```suggestion
    role: string;
```
This should be role since `UserSchema` use `role` not `role`, which leads to IDE wrongly suggest on `TestController`

2022-04-05 01:36 UTC, dangvuthang requested changes
Thank you for your hard word. Here are some problems that I found:

- Typo on `User` model lead to wrong suggestion in IDE
- Inconsistent `_id` and `link` when test is created in `createdTest`
- Using wrong route for `RecordRouter`
- Model `Submission` should have `record` field not the other way around

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/AuthController.ts
> +  if (user!.roles != "teacher") {
```suggestion
  if (user!.role !== "teacher") {
```
You have a typo here, thus causing the value to be `undefined` which cause the request to stop here in `/api/v1/tests`

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/AuthController.ts
> +    return res.status(400).json({
```suggestion
    return res.status(403).json({
```
Unauthorized request should be 403, 400 is only for Bad Request

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/TestController.ts
> +      errors: [
Not in a correct format

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/TestController.ts
> +      errors: [
Not correct format

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/TestController.ts
> +  link = "http://localhost:3000/exams/" + _id;
```suggestion
  link = "http://localhost:3000/exam/" + _id;
```
Should be exam

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/TestController.ts
> +    test = await Test.create({ name, startedDate, endDate, link, duration, question, teacherId })
You need to also include the `_id` when creating test to ensure the consistency between `link` and `_id` when document created

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/TestController.ts
> +      errors: [
not in the correct format

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/TestController.ts
> +      errors: [
not in the correct format

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/controllers/TestController.ts
> +      errors: [
not in the correct format

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/index.ts
> +app.use("/api/v1/submission", RecordRouter)
Wrong routes in line 20, it should be records

2022-04-05 01:36 UTC, dangvuthang commented on backend/src/index.ts
> +app.use("/api/v1/submission", SubmissionRouter)
All resources should be in plural noun

2022-04-05 02:31 UTC, merged